<?php
/**
 * Patch vendor/autoload.php for PrestaShop compatibility
 *
 * This script modifies the Composer-generated autoload.php to:
 * - In PrestaShop context: Register only the module's PSR-4 autoloader (no dev dependencies)
 * - Outside PrestaShop: Load full Composer autoloader as normal
 *
 * Run this after `composer install` or `composer update`:
 *   php scripts/patch-autoload.php
 *   OR
 *   composer run patch-autoload
 *
 * WHY IS THIS NEEDED?
 * PrestaShop automatically loads vendor/autoload.php from modules during kernel boot.
 * Dev dependencies (phpstan-symfony, php-cs-fixer) contain Symfony packages that
 * conflict with PrestaShop's Symfony version, causing fatal errors.
 */

declare(strict_types=1);

$vendorAutoload = dirname(__DIR__) . '/vendor/autoload.php';

if (!file_exists($vendorAutoload)) {
    echo "Error: vendor/autoload.php not found. Run 'composer install' first.\n";
    exit(1);
}

$content = file_get_contents($vendorAutoload);

// Check if already patched
if (strpos($content, 'PRESTASHOP_AUTOLOAD_PATCH') !== false) {
    echo "vendor/autoload.php is already patched for PrestaShop.\n";
    exit(0);
}

// Get the module namespace from composer.json
$composerJson = dirname(__DIR__) . '/composer.json';
$composer = json_decode(file_get_contents($composerJson), true);
$namespaces = array_keys($composer['autoload']['psr-4'] ?? []);
$mainNamespace = $namespaces[0] ?? 'WeprestaAcf\\';
$mainNamespace = rtrim($mainNamespace, '\\');

// Create the patch
$patch = <<<'PHP'
<?php

// autoload.php @generated by Composer
// PRESTASHOP_AUTOLOAD_PATCH: Modified for PrestaShop compatibility

// In PrestaShop context, register only the module's PSR-4 autoloader
// to avoid conflicts with dev dependencies that have different Symfony versions
if (defined('_PS_VERSION_')) {
    $globalKey = 'NAMESPACE_autoloader_registered';
    if (!isset($GLOBALS[$globalKey])) {
        $GLOBALS[$globalKey] = true;
        $moduleDir = dirname(__DIR__);

        spl_autoload_register(function ($class) use ($moduleDir) {
            $prefix = 'NAMESPACE\\';
            $len = strlen($prefix);

            if (strncmp($prefix, $class, $len) !== 0) {
                return false;
            }

            $baseDir = $moduleDir . '/src/';
            $relativeClass = substr($class, $len);
            $file = $baseDir . str_replace('\\', DIRECTORY_SEPARATOR, $relativeClass) . '.php';

            if (file_exists($file)) {
                require_once $file;
                return true;
            }

            return false;
        }, true, true);
    }
    return;
}

// Outside PrestaShop (CLI for dev tools): load full Composer autoloader

PHP;

// Replace NAMESPACE placeholder
$patch = str_replace('NAMESPACE', $mainNamespace, $patch);

// Find the line after the PHP opening tag in original content
$lines = explode("\n", $content);
$newContent = '';
$foundPhpTag = false;

foreach ($lines as $i => $line) {
    if (!$foundPhpTag && strpos($line, '<?php') !== false) {
        // Skip the original <?php and comments, we're replacing them
        $foundPhpTag = true;
        // Find where the actual code starts (skip comments)
        continue;
    }
    
    if ($foundPhpTag) {
        // Skip comment lines at the beginning
        $trimmed = trim($line);
        if (empty($trimmed) || strpos($trimmed, '//') === 0) {
            continue;
        }
        
        // Found actual code, start from here
        $newContent = $patch . implode("\n", array_slice($lines, $i));
        break;
    }
}

if (empty($newContent)) {
    $newContent = $patch . $content;
}

file_put_contents($vendorAutoload, $newContent);

echo "✓ vendor/autoload.php patched for PrestaShop compatibility.\n";
echo "  Module namespace: {$mainNamespace}\n";


